---
slug: :mikutter-webapi-hardpoint
depends:
  mikutter: 3.3.0
  plugin:
  - gui
version: '0.0.4'
author: 
name: mikutter-webapi-hardpoint
description: 'Chromeとかと会話するためのWebAPIを提供する前提プラグイン。Chromeで見てるURLをmikutterに送るサンプル付き。'
